name: Rust CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        rust: ["1.34.2", stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: build
      run: |
        cargo build --verbose
        cargo doc --verbose
  mips_cross:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: add_cross_target
      run: |
        rustup target add mips64-unknown-linux-gnuabi64
        cargo build --all-features --target mips64-unknown-linux-gnuabi64
  test_all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup default stable
    - name: test
      run: >
        cargo test -v --all-targets --all-features
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    - name: Run rustfmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
